# Generated by Django 4.1.2 on 2022-10-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expire_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
